import React, {useEffect, useRef, useState} from 'react';
import {View, Text, TextInput, Image, ImageBackground, ScrollView, Pressable, StyleSheet, useWindowDimensions, Platform, Linking, Share, ActivityIndicator, KeyboardAvoidingView, StatusBar} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {Ionicons} from '@expo/vector-icons';
import {useFonts,Vazirmatn_400Regular,Vazirmatn_700Bold,Vazirmatn_900Black} from '@expo-google-fonts/vazirmatn';
import {catalog,categories,templates,normalizeDigits,safeUrl,logoUrl,buildPrompt} from './catalog';
import {discover} from './discovery';
import {api} from './api';

const hero = require('../assets/persepolis-home.png');
const splash = require('../assets/persepolis-hero.png');
const KEY = 'parsai:preferences:v2';
const C = {bg:'#041923',panel:'#0c2733',line:'#284854',gold:'#efbd69',text:'#f4f0e5',muted:'#9bb1b8'};
function Logo({tool,size=52}) {
  const [failed,setFailed] = useState(false);
  const uri=logoUrl(tool);
  useEffect(()=>setFailed(false),[uri]);
  return <View style={{width:size,height:size,borderRadius:15,backgroundColor:'#16333e',alignItems:'center',justifyContent:'center',overflow:'hidden'}}>{uri&&!failed?<Image accessibilityLabel={`${tool.name} website logo`} source={{uri}} style={{width:size-12,height:size-12}} resizeMode="contain" onError={()=>setFailed(true)}/>:<Text style={{color:C.gold,fontSize:size/3,fontWeight:'bold'}}>{tool.name.slice(0,2).toUpperCase()}</Text>}</View>;
}
export default function ParsApp() {
  const {width}=useWindowDimensions();
  const [fonts]=useFonts({Vazirmatn_400Regular,Vazirmatn_700Bold,Vazirmatn_900Black});
  const [ready,setReady]=useState(false),[lang,setLang]=useState('fa'),[page,setPage]=useState('welcome');
  const [phone,setPhone]=useState(''),[otp,setOtp]=useState(''),[logged,setLogged]=useState(false);
  const [favorites,setFavorites]=useState([]),[savedPrompts,setSavedPrompts]=useState([]);
  const [category,setCategory]=useState('all'),[query,setQuery]=useState(''),[tab,setTab]=useState('editorial');
  const [selected,setSelected]=useState(null),[detailTab,setDetailTab]=useState('about');
  const [remote,setRemote]=useState([]),[remoteInfo,setRemoteInfo]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const [idea,setIdea]=useState(''),[style,setStyle]=useState('cinematic'),[ratio,setRatio]=useState('16:9'),[result,setResult]=useState('');
  const [promptCategory,setPromptCategory]=useState('all'),[favoriteTab,setFavoriteTab]=useState('tools');
  const [message,setMessage]=useState(''),[messages,setMessages]=useState([]);
  const request=useRef(null),noticeTimer=useRef(null);
  const fa=lang==='fa', tr=(a,b)=>fa?a:b;
  const direction={flexDirection:fa?'row-reverse':'row'}, align={textAlign:fa?'right':'left',writingDirection:fa?'rtl':'ltr'};
  const demo=process.env.EXPO_PUBLIC_DEMO_AUTH!=='false';
  useEffect(()=>{let active=true; AsyncStorage.getItem(KEY).then(raw=>{if(!active||!raw)return; const p=JSON.parse(raw);setLang(p.lang==='en'?'en':'fa');setFavorites(Array.isArray(p.favorites)?p.favorites:[]);setSavedPrompts(Array.isArray(p.savedPrompts)?p.savedPrompts:[]);}).catch(()=>{}).finally(()=>active&&setReady(true));return()=>{active=false;request.current?.abort();clearTimeout(noticeTimer.current)}},[]);
  useEffect(()=>{if(ready)AsyncStorage.setItem(KEY,JSON.stringify({lang,favorites,savedPrompts})).catch(()=>{})},[ready,lang,favorites,savedPrompts]);
  function notify(text){setNotice(text);clearTimeout(noticeTimer.current);noticeTimer.current=setTimeout(()=>setNotice(''),5500)}
  function go(next){setNotice('');setPage(next)}
  async function openUrl(url){const safe=safeUrl(url);if(!safe)return notify(tr('این نشانی معتبر نیست.','Invalid website address.'));try{await Linking.openURL(safe)}catch{notify(tr('بازکردن سایت ممکن نشد.','Could not open website.'))}}
  function toggle(tool){setFavorites(prev=>prev.some(x=>x.id===tool.id)?prev.filter(x=>x.id!==tool.id):[tool,...prev]);}
  async function copy(text){try{if(Platform.OS==='web'&&globalThis.navigator?.clipboard){await navigator.clipboard.writeText(text);notify(tr('کپی شد ✓','Copied ✓'))}else {await Share.share({message:text})}}catch{notify(tr('کپی انجام نشد؛ متن را نگه دار و انتخاب کن.','Could not copy. Select the text manually.'))}}
  async function login(){if(!phone.trim())return notify(tr('یک شماره آزمایشی وارد کن.','Enter a test number.'));if(demo){setOtp('');go('otp');return;}try{setBusy(true);await api.requestOtp(phone,lang);go('otp')}catch{notify(tr('ارسال پیامک ممکن نشد. اتصال سرور را بررسی کن.','SMS unavailable. Check the server connection.'))}finally{setBusy(false)}}
  async function verify(){if(demo){if(normalizeDigits(otp)!=='1234')return notify(tr('کد آزمایشی 1234 است.','The demo code is 1234.'));setLogged(true);go('home');return;}try{setBusy(true);await api.verifyOtp(phone,otp,lang);setLogged(true);go('home')}catch{notify(tr('کد معتبر نیست یا اتصال برقرار نشد.','Invalid code or connection unavailable.'))}finally{setBusy(false)}}
  async function refresh(){request.current?.abort();const ctl=new AbortController();request.current=ctl;setBusy(true);setRemote([]);setRemoteInfo(null);try{const data=await discover(category,query,ctl.signal);if(!ctl.signal.aborted){setRemote(data.tools);setRemoteInfo(data)}}catch{if(!ctl.signal.aborted)notify(tr('منبع آنلاین در دسترس نیست. ابزارهای منتخب همچنان قابل استفاده‌اند.','Online source unavailable. The curated catalog is still available.'))}finally{if(!ctl.signal.aborted)setBusy(false)}}
  function chooseCategory(id){request.current?.abort();setBusy(false);setCategory(id);setQuery('');setRemote([]);setRemoteInfo(null);go('tools')}
  function selectTool(tool){setSelected(tool);setDetailTab('about');go('detail')}
  function savePrompt(){if(!result)return;setSavedPrompts(p=>[{id:String(Date.now()),text:result},...p].slice(0,100));notify(tr('پرامپت ذخیره شد.','Prompt saved.'))}
  function send(){if(!message.trim())return;const q=message.trim().toLowerCase();let cat=categories.find(x=>x[0]!=='all'&&(q.includes(x[1])||q.includes(x[2].toLowerCase())))?.[0];if(/عکس|تصویر|image|photo/.test(q))cat='image';if(/کد|برنامه|code|react/.test(q))cat='code';if(/وید|video/.test(q))cat='video';if(/موسیقی|صدا|music|audio/.test(q))cat='audio';const picks=catalog.filter(x=>!cat||x.category===cat).slice(0,3);setMessages(p=>[...p,{id:Date.now(),question:message,tools:picks}]);setMessage('')}
  const label=id=>{const c=categories.find(x=>x[0]===id);return c?c[fa?1:2]:id};
  const Txt=({children,style:st,...props})=><Text {...props} style={[s.text,align,st]}>{children}</Text>;
  const Button=({title,onPress,icon='arrow-forward',secondary=false,disabled=false})=><Pressable accessibilityRole="button" onPress={onPress} disabled={disabled} style={({pressed})=>[s.button,secondary&&s.secondary,direction,{opacity:disabled?.45:pressed?.75:1}]}><Ionicons name={icon} size={19} color={secondary?C.gold:C.bg}/><Txt style={[s.buttonText,secondary&&{color:C.gold}]}>{title}</Txt></Pressable>;
  const Chips=({items,value,onChange})=><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={[s.chips,direction]}>{items.map(([id,name])=><Pressable accessibilityRole="button" accessibilityState={{selected:value===id}} key={id} onPress={()=>onChange(id)} style={[s.chip,value===id&&s.chipOn]}><Txt style={{fontSize:12,color:value===id?C.bg:C.muted}}>{name}</Txt></Pressable>)}</ScrollView>;
  const Tool=({tool})=><Pressable accessibilityRole="button" onPress={()=>selectTool(tool)} style={({pressed})=>[s.card,direction,{opacity:pressed?.75:1}]}><Logo tool={tool}/><View style={{flex:1,gap:5}}><Txt style={s.cardTitle}>{tool.name}</Txt><Txt style={s.small}>{label(tool.category)}{tool.source==='huggingface'?` · ↓ ${tool.downloads.toLocaleString()}`:''}</Txt><Txt numberOfLines={2} style={s.description}>{tool.description[lang]}</Txt></View><Ionicons name={fa?'chevron-back':'chevron-forward'} color={C.gold} size={18}/></Pressable>;
  const PromptList=()=> <>{templates.filter(x=>promptCategory==='all'||x.category===promptCategory).map(item=><View key={item.id} style={s.panel}><View style={[direction,{alignItems:'center',gap:12}]}><Ionicons name={categories.find(c=>c[0]===item.category)?.[3]} size={27} color={C.gold}/><View style={{flex:1}}><Txt style={s.cardTitle}>{item[lang]}</Txt><Txt style={s.small}>{label(item.category)}</Txt></View></View><Txt selectable style={[s.description,{marginTop:14,textAlign:'left',writingDirection:'ltr'}]}>{item.prompt}</Txt><View style={[direction,{gap:10}]}><View style={{flex:1}}><Button secondary title={tr('کپی / اشتراک','Copy / share')} icon="copy-outline" onPress={()=>copy(item.prompt)}/></View><View style={{flex:1}}><Button title={tr('استفاده','Use')} icon="color-wand-outline" onPress={()=>{setIdea(item.prompt);go('builder')}}/></View></View></View>)}</>;
  if(!fonts||!ready)return <View style={[s.root,{justifyContent:'center'}]}><ActivityIndicator color={C.gold}/></View>;
  let content;
  if(page==='welcome') content=<ImageBackground source={splash} style={s.fill}><View style={s.veil}/><View style={s.splashBrand}><Txt style={s.wordmark}>Pars AI</Txt><Txt style={{textAlign:'center',color:C.gold,letterSpacing:4}}>DISCOVER · CREATE · INSPIRE</Txt></View><View style={s.splashBottom}><Txt style={[s.title,{textAlign:'center'}]}>{tr('از شکوه گذشته، برای آینده','Inspired by history. Built for tomorrow.')}</Txt><Txt style={[s.description,{textAlign:'center',marginBottom:20}]}>{tr('ابزار مناسب را پیدا کن، ایده‌ات را بساز.','Find your tool. Bring your idea to life.')}</Txt><Button title={tr('شروع کاوش','Start exploring')} onPress={()=>go('language')}/></View></ImageBackground>;
  else if(['language','phone','otp'].includes(page)) content=<ImageBackground source={hero} style={[s.fill,{justifyContent:'center',padding:22}]}><View style={s.veil}/><View style={s.auth}><Txt style={[s.title,{textAlign:'center',color:C.gold}]}>Pars AI</Txt>{page==='language'?<><Txt style={[s.title,{textAlign:'center'}]}>{tr('زبانت را انتخاب کن','Choose your language')}</Txt><Button title="فارسی" icon={fa?'checkmark-circle':'language'} secondary={!fa} onPress={()=>setLang('fa')}/><Button title="English" icon={!fa?'checkmark-circle':'language'} secondary={fa} onPress={()=>setLang('en')}/><Button title={tr('ادامه','Continue')} onPress={()=>go(logged?'home':'phone')}/></>:<><Txt style={[s.title,{textAlign:'center'}]}>{page==='phone'?tr('خوش آمدی','Welcome'):tr('کد ورود','Verification code')}</Txt><Txt style={[s.description,{textAlign:'center',marginBottom:18}]}>{demo?tr('ورود آزمایشی • هیچ پیامکی ارسال نمی‌شود','Demo access • No SMS will be sent'):tr('ورود با شماره موبایل','Sign in with your phone')}</Txt><TextInput accessibilityLabel={page==='phone'?'Phone number':'Verification code'} value={page==='phone'?phone:otp} onChangeText={value=>page==='phone'?setPhone(normalizeDigits(value)):setOtp(normalizeDigits(value))} keyboardType="number-pad" maxLength={page==='phone'?13:6} placeholder={page==='phone'?'09120000000':'1234'} placeholderTextColor={C.muted} style={[s.input,{textAlign:'center'}]} onSubmitEditing={page==='phone'?login:verify}/>{demo&&page==='otp'&&<Txt style={[s.small,{textAlign:'center',marginTop:10}]}>{tr('کد آزمایشی: 1234','Demo code: 1234')}</Txt>}<Button disabled={busy} title={busy?tr('لطفاً صبر کن…','Please wait…'):tr('ادامه','Continue')} onPress={page==='phone'?login:verify}/>{demo&&<Button secondary title={tr('کاوش بدون شماره','Explore as guest')} icon="compass-outline" onPress={()=>{setLogged(true);go('home')}}/>}<Button secondary title={tr('بازگشت','Back')} icon="arrow-back" onPress={()=>go(page==='otp'?'phone':'language')}/></>}</View></ImageBackground>;
  else {
    let body;
    if(page==='home')body=<><ImageBackground source={hero} style={s.hero}><View style={s.veil}/><View style={{padding:22,gap:12}}><Txt style={s.eyebrow}>PARS AI / DISCOVERY</Txt><Txt style={s.heroTitle}>{tr('ایده از تو،\nابزارش با ما.','Your next idea.\nYour next AI tool.')}</Txt><Txt style={s.description}>{tr('یک راهنمای ایرانی برای دنیای هوش مصنوعی','An Iranian-inspired guide to artificial intelligence')}</Txt><Button title={tr('چه کاری می‌خواهی انجام بدهی؟','What would you like to create?')} icon="search-outline" onPress={()=>go('tools')}/></View></ImageBackground><View style={[s.grid,direction]}>{categories.slice(1).map(c=><Pressable accessibilityRole="button" key={c[0]} style={s.category} onPress={()=>chooseCategory(c[0])}><Ionicons name={c[3]} color={C.gold} size={30}/><Txt style={{textAlign:'center',fontSize:12,marginTop:12}}>{c[fa?1:2]}</Txt></Pressable>)}</View><View style={s.panel}><Txt style={s.title}>{tr('از ایده تا پرامپت','From idea to prompt')}</Txt><Txt style={s.description}>{tr('قالب‌های کاربردی، قابل ویرایش و بدون هزینه','Useful, editable templates at no cost')}</Txt><Button title={tr('ساخت پرامپت','Build a prompt')} icon="sparkles-outline" onPress={()=>go('builder')}/></View><Txt style={s.section}>{tr('ابزارهای منتخب','Curated tools')}</Txt>{catalog.slice(0,3).map(tool=><Tool key={tool.id} tool={tool}/>)}<Button secondary title={tr('کشف مدل‌های آنلاین','Discover models online')} icon="globe-outline" onPress={()=>{setTab('online');chooseCategory('all')}}/></>;
    else if(page==='tools')body=<><Txt style={s.title}>{tr('ابزار مناسب تو','Find your next tool')}</Txt><Txt style={s.description}>{tr('سایت‌های منتخب و مدل‌های عمومی؛ دو مسیر برای کشف','Curated websites and public models, two ways to discover')}</Txt><Chips items={[['editorial',tr('ابزارهای منتخب','Curated tools')],['online',tr('مدل‌های آنلاین','Online models')]]} value={tab} onChange={setTab}/><Chips items={categories.map(c=>[c[0],c[fa?1:2]])} value={category} onChange={chooseCategory}/><TextInput accessibilityLabel="Search tools" style={[s.input,align]} placeholder={tr('جستجو با نام ابزار یا مدل…','Search a tool or model name…')} placeholderTextColor={C.muted} value={query} onChangeText={setQuery} onSubmitEditing={()=>tab==='online'&&refresh()}/>{tab==='online'?<><Txt style={[s.small,{marginVertical:12}]}>{tr('منبع: Hugging Face • مرتب بر اساس دانلود. اطلاعات رایگان است؛ اجرای مدل ممکن است هزینه یا محدودیت داشته باشد.','Source: Hugging Face • Sorted by downloads. Catalog access is free; model execution may have costs or restrictions.')}</Txt><Button disabled={busy} icon="refresh-outline" title={busy?tr('در حال دریافت…','Loading…'):tr('دریافت از API عمومی','Fetch public API')} onPress={refresh}/>{remoteInfo&&<Txt style={s.small}>{tr(remoteInfo.cached?'نسخه ذخیره‌شده • ':'دریافت آنلاین • ',remoteInfo.cached?'Cached • ':'Online • ')}{new Date(remoteInfo.updatedAt).toLocaleString(fa?'fa-IR':'en-US')}</Txt>}{remote.map(tool=><Tool key={tool.id} tool={tool}/>)}{!busy&&remoteInfo&&!remote.length&&<Txt style={s.empty}>{tr('مدلی با این نام پیدا نشد. نام انگلیسی را امتحان کن.','No models found. Try another model name.')}</Txt>}<Button secondary title="Hugging Face ↗" icon="open-outline" onPress={()=>openUrl('https://huggingface.co/models')}/></>:<>{catalog.filter(x=>(category==='all'||x.category===category)&&`${x.name} ${x.description[lang]}`.toLowerCase().includes(query.toLowerCase())).map(tool=><Tool key={tool.id} tool={tool}/>)}{!catalog.some(x=>(category==='all'||x.category===category)&&`${x.name} ${x.description[lang]}`.toLowerCase().includes(query.toLowerCase()))&&<Txt style={s.empty}>{tr('نتیجه‌ای پیدا نشد.','No results found.')}</Txt>}</>}</>;
    else if(page==='detail'&&selected)body=<><ImageBackground source={hero} style={[s.hero,{minHeight:150}]}><View style={s.veil}/><View style={[direction,{padding:24,alignItems:'center',gap:16}]}><Logo tool={selected} size={76}/><View style={{flex:1}}><Txt style={s.title}>{selected.name}</Txt><Txt style={s.eyebrow}>{label(selected.category)}</Txt></View></View></ImageBackground><Chips value={detailTab} onChange={setDetailTab} items={[['about',tr('معرفی','Overview')],['prompts',tr('پرامپت مرتبط','Related prompts')]]}/>{detailTab==='about'?<View style={s.panel}><Txt style={s.description}>{selected.description[lang]}</Txt><Txt style={[s.small,{marginTop:16}]}>{tr('قیمت، دسترسی و مجوز استفاده را در سایت رسمی بررسی کن.','Check pricing, availability and licensing on the official website.')}</Txt>{selected.downloads!==undefined&&<Txt style={s.small}>↓ {selected.downloads.toLocaleString()} · ♥ {selected.likes.toLocaleString()}</Txt>}<Txt style={[s.small,{marginTop:12}]}>{selected.website}</Txt></View>:templates.filter(x=>x.category===selected.category).map(x=><View style={s.panel} key={x.id}><Txt style={s.cardTitle}>{x[lang]}</Txt><Txt selectable style={s.description}>{x.prompt}</Txt><Button secondary title={tr('کپی / اشتراک','Copy / share')} icon="copy-outline" onPress={()=>copy(x.prompt)}/></View>)}<Button title={tr('باز کردن سایت','Open website')} icon="open-outline" onPress={()=>openUrl(selected.website)}/><Button secondary title={favorites.some(x=>x.id===selected.id)?tr('حذف از علاقه‌مندی‌ها','Remove favorite'):tr('ذخیره در علاقه‌مندی‌ها','Save favorite')} icon="heart-outline" onPress={()=>toggle(selected)}/><Button secondary title={tr('اشتراک‌گذاری ابزار','Share tool')} icon="share-outline" onPress={()=>copy(`${selected.name}\n${selected.website}`)}/></>;
    else if(page==='prompts')body=<><Txt style={s.title}>{tr('کتابخانه پرامپت','Prompt library')}</Txt><Txt style={s.description}>{tr('جای عبارت‌های داخل [ ] را با ایده خودت پر کن.','Replace the [placeholders] with your own ideas.')}</Txt><Button title={tr('ساخت پرامپت جدید','Create a prompt')} icon="add" onPress={()=>go('builder')}/><Chips items={categories.map(c=>[c[0],c[fa?1:2]])} value={promptCategory} onChange={setPromptCategory}/><PromptList/></>;
    else if(page==='builder')body=<><Txt style={s.title}>{tr('ایده‌ات را دقیق‌تر کن','Give your idea direction')}</Txt><Txt style={s.description}>{tr('سازنده قالب رایگان • بدون نیاز به API پولی','Free template builder • No paid API required')}</Txt><TextInput accessibilityLabel="Prompt idea" style={[s.input,align,{minHeight:150,textAlignVertical:'top',marginTop:20}]} placeholder={tr('موضوع، محصول، محیط و جزئیات موردنظرت…','Subject, product, setting, and details…')} placeholderTextColor={C.muted} multiline value={idea} onChangeText={setIdea}/><Txt style={s.section}>{tr('سبک','Style')}</Txt><Chips items={[['cinematic',tr('سینمایی','Cinematic')],['realistic',tr('واقع‌گرایانه','Realistic')],['editorial',tr('تبلیغاتی','Editorial')],['minimal',tr('مینیمال','Minimal')]]} value={style} onChange={setStyle}/><Txt style={s.section}>{tr('نسبت تصویر','Aspect ratio')}</Txt><Chips items={['16:9','1:1','9:16','4:3'].map(x=>[x,x])} value={ratio} onChange={setRatio}/><Button title={tr('ساخت پرامپت','Build prompt')} icon="sparkles-outline" onPress={()=>idea.trim()?setResult(buildPrompt(idea,style,ratio,lang)):notify(tr('اول ایده‌ات را بنویس.','Describe your idea first.'))}/>{result&&<View style={s.panel}><Txt style={s.eyebrow}>{tr('پرامپت آماده','YOUR PROMPT')}</Txt><Txt selectable style={[s.description,{marginTop:12}]}>{result}</Txt><Button title={tr('کپی / اشتراک','Copy / share')} icon="copy-outline" onPress={()=>copy(result)}/><Button secondary title={tr('ذخیره پرامپت','Save prompt')} icon="bookmark-outline" onPress={savePrompt}/><Button secondary title={tr('پیداکردن ابزار','Find a tool')} icon="search-outline" onPress={()=>chooseCategory('image')}/></View>}</>;
    else if(page==='favorites')body=<><Txt style={s.title}>{tr('مجموعه شخصی تو','Your collection')}</Txt><Chips items={[['tools',tr('ابزارها','Tools')],['prompts',tr('پرامپت‌ها','Prompts')]]} value={favoriteTab} onChange={setFavoriteTab}/>{favoriteTab==='tools'?favorites.length?favorites.map(tool=><Tool key={tool.id} tool={tool}/>):<Txt style={s.empty}>{tr('هنوز ابزاری ذخیره نکرده‌ای. از صفحه هر ابزار، قلب را بزن.','No saved tools yet. Save one from its detail page.')}</Txt>:savedPrompts.length?savedPrompts.map(p=><View style={s.panel} key={p.id}><Txt selectable style={s.description}>{p.text}</Txt><Button title={tr('کپی / اشتراک','Copy / share')} icon="copy-outline" onPress={()=>copy(p.text)}/><Button secondary title={tr('حذف','Remove')} icon="trash-outline" onPress={()=>setSavedPrompts(prev=>prev.filter(x=>x.id!==p.id))}/></View>):<Txt style={s.empty}>{tr('هنوز پرامپتی ذخیره نکرده‌ای.','No saved prompts yet.')}</Txt>}</>;
    else if(page==='chat')body=<><Txt style={s.title}>{tr('راهنمای انتخاب ابزار','Tool finder')}</Txt><Txt style={s.description}>{tr('راهنمای محلی بر اساس دسته‌بندی؛ پاسخ مدل زبانی آنلاین نیست. برای مدل‌های جدید از کشف آنلاین استفاده کن.','Local category-based guidance, not an online language model. Use online discovery for current models.')}</Txt>{messages.map(m=><View key={m.id} style={s.panel}><Txt style={[s.cardTitle,{color:C.gold,marginBottom:12}]}>{m.question}</Txt>{m.tools.map(tool=><Tool key={tool.id} tool={tool}/>)}</View>)}<TextInput accessibilityLabel="Ask tool finder" style={[s.input,align,{marginTop:20}]} placeholder={tr('مثلاً برای ساخت عکس چه ابزاری هست؟','For example: tools for creating images?')} placeholderTextColor={C.muted} value={message} onChangeText={setMessage} onSubmitEditing={send}/><Button title={tr('پیشنهاد ابزار','Find tools')} icon="send-outline" onPress={send}/></>;
    else body=<><Txt style={s.title}>{tr('تنظیمات','Settings')}</Txt><View style={s.panel}><Txt style={s.section}>{tr('زبان برنامه','App language')}</Txt><Chips items={[['fa','فارسی'],['en','English']]} value={lang} onChange={setLang}/><Txt style={s.description}>{tr('داده‌های علاقه‌مندی و زبان روی همین دستگاه ذخیره می‌شوند.','Your favorites and language are saved on this device.')}</Txt></View><View style={s.panel}><Txt style={s.cardTitle}>{tr('درباره Pars AI','About Pars AI')}</Txt><Txt style={s.description}>{tr('راهنمای ابزارهای هوش مصنوعی با هویت ایرانی. تصاویر کوچک، لوگوی سایت ابزارها هستند. این برنامه وابسته به آن برندها نیست.','An Iranian-inspired AI discovery app. Thumbnails are website logos. Pars AI is not affiliated with these brands.')}</Txt><Txt style={[s.small,{marginTop:14}]}>{tr('نسخه آزمایشی • ورود نمایشی • اطلاعات آنلاین از Hugging Face. دسترسی شبکه و خدمات رایگان تضمین نمی‌شود.','Preview version • Demo login • Online catalog from Hugging Face. Network access and free services are not guaranteed.')}</Txt></View><Button secondary title={tr('خروج','Sign out')} icon="log-out-outline" onPress={()=>{setLogged(false);setPhone('');setOtp('');go('language')}}/></>;
    const nav=[['home','home-outline','خانه','Home'],['tools','compass-outline','کشف','Discover'],['prompts','albums-outline','پرامپت','Prompts'],['favorites','heart-outline','ذخیره‌ها','Saved'],['chat','chatbubbles-outline','راهنما','Guide']];
    content=<><View style={[s.header,direction]}><Pressable accessibilityLabel="Settings" onPress={()=>go(page==='settings'?'home':'settings')} style={s.iconButton}><Ionicons name={page==='settings'?'close-outline':'settings-outline'} size={24} color={C.gold}/></Pressable><Text style={s.brand}>Pars AI <Text style={{fontSize:10,color:C.muted}}> / DISCOVER</Text></Text>{['detail','builder','settings'].includes(page)?<Pressable accessibilityLabel="Back" style={s.iconButton} onPress={()=>go(page==='detail'?'tools':page==='builder'?'prompts':'home')}><Ionicons name="arrow-back" color={C.gold} size={23}/></Pressable>:<View style={s.iconButton}/>}</View><ScrollView key={page} keyboardShouldPersistTaps="handled" contentContainerStyle={s.content}>{body}</ScrollView><View style={[s.nav,direction]}>{nav.map(([id,icon,faLabel,enLabel])=><Pressable accessibilityRole="button" accessibilityLabel={fa?faLabel:enLabel} key={id} onPress={()=>go(id)} style={s.navItem}><Ionicons name={icon} size={23} color={page===id?C.gold:C.muted}/><Txt style={{fontSize:10,textAlign:'center',color:page===id?C.gold:C.muted}}>{fa?faLabel:enLabel}</Txt>{page===id&&<View style={s.activeDot}/>}</Pressable>)}</View></>;
  }
  return <View style={s.root}><StatusBar barStyle="light-content" backgroundColor={C.bg}/><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={[s.app,{width:Math.min(width,600),paddingTop:Platform.OS==='android'?(StatusBar.currentHeight||0):0}]}>{content}{notice?<Pressable accessibilityRole="alert" onPress={()=>setNotice('')} style={s.toast}><Text style={[s.text,align]}>{notice}</Text></Pressable>:null}</KeyboardAvoidingView></View>;
}
const s=StyleSheet.create({
 root:{flex:1,backgroundColor:'#020f17',alignItems:'center'},app:{flex:1,backgroundColor:C.bg,overflow:'hidden'},fill:{flex:1,justifyContent:'space-between'},veil:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(2,17,26,.47)'},text:{fontFamily:'Vazirmatn_400Regular',color:C.text,fontSize:14},title:{fontFamily:'Vazirmatn_900Black',fontSize:23,lineHeight:36,marginBottom:8},wordmark:{fontSize:55,color:C.gold,fontFamily:'Vazirmatn_900Black',textAlign:'center'},splashBrand:{paddingTop:65},splashBottom:{padding:28,paddingBottom:38},auth:{padding:24,borderWidth:1,borderColor:'#79603a',borderRadius:25,backgroundColor:'rgba(4,25,35,.96)'},header:{height:65,paddingHorizontal:14,alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderColor:C.line},brand:{color:C.gold,fontSize:22,fontWeight:'900',letterSpacing:1},iconButton:{width:40,height:44,justifyContent:'center',alignItems:'center'},content:{padding:16,paddingBottom:30},hero:{minHeight:230,borderRadius:22,overflow:'hidden',justifyContent:'flex-end',marginBottom:18},heroTitle:{fontFamily:'Vazirmatn_900Black',fontSize:30,lineHeight:46,color:'#fff9eb'},eyebrow:{color:C.gold,fontSize:11,fontFamily:'Vazirmatn_700Bold',letterSpacing:1},description:{fontSize:13,lineHeight:23,color:'#bbccd0'},small:{fontSize:11,color:C.muted,lineHeight:20},section:{fontFamily:'Vazirmatn_700Bold',fontSize:18,marginVertical:16,color:C.gold},grid:{flexWrap:'wrap',gap:9,marginBottom:14},category:{width:'31%',flexGrow:1,borderWidth:1,borderColor:C.line,borderRadius:16,paddingVertical:20,alignItems:'center',backgroundColor:'#09232e'},panel:{padding:18,marginTop:14,marginBottom:6,borderRadius:19,backgroundColor:C.panel,borderWidth:1,borderColor:C.line},card:{padding:15,marginTop:12,gap:13,alignItems:'center',backgroundColor:C.panel,borderWidth:1,borderColor:C.line,borderRadius:18},cardTitle:{fontSize:15,fontFamily:'Vazirmatn_700Bold'},button:{minHeight:48,padding:12,borderRadius:13,backgroundColor:C.gold,alignItems:'center',justifyContent:'center',gap:9,marginTop:14},buttonText:{color:C.bg,fontFamily:'Vazirmatn_700Bold',fontSize:13},secondary:{backgroundColor:'transparent',borderWidth:1,borderColor:'#665337'},input:{minHeight:51,padding:14,borderWidth:1,borderColor:C.line,borderRadius:14,color:C.text,backgroundColor:'#0b2531',fontFamily:'Vazirmatn_400Regular',fontSize:14},chips:{gap:8,paddingVertical:15},chip:{paddingHorizontal:15,paddingVertical:9,borderRadius:20,borderWidth:1,borderColor:C.line,backgroundColor:C.panel},chipOn:{backgroundColor:C.gold,borderColor:C.gold},nav:{minHeight:76,paddingTop:12,paddingBottom:12,borderTopWidth:1,borderColor:C.line,backgroundColor:'#061e28'},navItem:{flex:1,alignItems:'center',gap:5},activeDot:{height:3,width:16,borderRadius:4,backgroundColor:C.gold},empty:{paddingVertical:36,color:C.muted,textAlign:'center',lineHeight:26},toast:{position:'absolute',bottom:90,left:18,right:18,padding:16,backgroundColor:'#254654',borderRadius:15,borderWidth:1,borderColor:C.gold}
});
